quarkus:
  devservices:
    enabled: false

  swagger-ui:
    always-include: true
  http:
    root-path: /${project.artifactId}

  application:
    name: @project.artifactId@

  spring-cloud-config:
    enabled: true
    url: https://localhost:8080/spring-config/