CREATE TABLE IF NOT EXISTS PUBLIC.SEND_ENTRY_ORDER_HJ_LOG
(
    ID SERIAL NOT NULL,
    ENTRY_ORDER_CODE VARCHAR(20) NOT NULL,
    SEND_DATE TIMESTAMP NOT NULL,
    RETURN_STATUS INTEGER NOT NULL,
    RESPONSE_MESSAGE JSON,
    CONSTRAINT SEND_ENTRY_ORDER_HJ_LOG_PKEY PRIMARY KEY (id)
);
