CREATE TABLE IF NOT EXISTS PUBLIC.ENTRY_ORDER_RECEIPT_CONFIRMATION_LOG
(
    ID SERIAL NOT NULL,
    MESSAGE_ID VARCHAR(100) NOT NULL,
    RECEIPT_DATE TIMESTAMP NOT NULL,
    RETURN_STATUS INTEGER NOT NULL,
    ERROR_MESSAGE JSON,
    CONSTRAINT ENTRY_ORDER_RECEIPT_CONFIRMATION_LOG_PKEY PRIMARY KEY (id)
);