CREATE TABLE IF NOT EXISTS PUBLIC.SENT_PRODUCT_RENOVA_LOG
(
    ID SERIAL NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    SENT BOOLEAN,
    SHIPPING_DATE TIMESTAMP NOT NULL,
    MESSAGE VARCHAR(100) NOT NULL,
    CONSTRAINT SENT_PRODUCT_RENOVA_LOG_PKEY PRIMARY KEY (id)
);